# Generated by Django 6.0.5 on 2026-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0003_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
